<a href="https://colab.research.google.com/github/khalida2025cse-sudo/FDS_Lab_Experiments/blob/main/Exp_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a random array of 9 elements
arr = np.random.randint(1, 100, size=9)
print("Original Array:")
print(arr)

# Find square roots
print("\nSquare Root:")
print(np.sqrt(arr))

# Find array dimension
print("\nArray Dimension:")
print(arr.ndim)

# Convert into a 3x3 matrix
matrix = arr.reshape(3, 3)
print("\n3x3 Matrix:")
print(matrix)

# Check matrix dimension
print("\nMatrix Dimension:")
print(matrix.ndim)

# Flatten the matrix
flat_arr = matrix.flatten()
print("\nFlattened Array:")
print(flat_arr)

# Reshape the matrix
reshaped = matrix.reshape(3, 3)
print("\nReshaped Matrix:")
print(reshaped)

# Access selected elements
print("\nLast Row, Second and Third Elements:")
print(reshaped[2, 1:3])

print("\nSecond Row, Second and Third Elements:")
print(reshaped[1:2, 1:3])

# Select an empty slice
print("\nEmpty Slice:")
print(matrix[:, 0:0])

# Select the first column of the first two rows
print("\nFirst Column of First Two Rows:")
print(matrix[0:2, 0:1])

# Select the first column of all rows
print("\nFirst Column:")
print(matrix[:, 0:1])

# Select the last two rows
print("\nLast Two Rows:")
print(matrix[1:3])

Original Array:
[25  8 37 67 84 60  5 95 24]

Square Root:
[5.         2.82842712 6.08276253 8.18535277 9.16515139 7.74596669
 2.23606798 9.74679434 4.89897949]

Array Dimension:
1

3x3 Matrix:
[[25  8 37]
 [67 84 60]
 [ 5 95 24]]

Matrix Dimension:
2

Flattened Array:
[25  8 37 67 84 60  5 95 24]

Reshaped Matrix:
[[25  8 37]
 [67 84 60]
 [ 5 95 24]]

Last Row, Second and Third Elements:
[95 24]

Second Row, Second and Third Elements:
[[84 60]]

Empty Slice:
[]

First Column of First Two Rows:
[[25]
 [67]]

First Column:
[[25]
 [67]
 [ 5]]

Last Two Rows:
[[67 84 60]
 [ 5 95 24]]
