<a href="https://colab.research.google.com/github/khalida2025cse-sudo/FDS_Lab_Experiments/blob/main/Exp_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Country': ['UK', 'Canada', 'Australia', 'Canada', 'UK',
                'Australia', 'Canada', 'UK', np.nan, 'Australia'],
    'Age': [24, 31, 26, 43, 34, np.nan, 40, 28, 52, 37],
    'Salary': [30000, 57000, 43000, np.nan, 49000,
               61000, 73000, 36000, 91000, 67000],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'No',
                  'Yes', 'No', 'Yes', 'No', 'Yes']
})

print("Original Data:")
print(df)

df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

features = df.iloc[:, :-1].values
label = df.iloc[:, -1].values

from sklearn.impute import SimpleImputer

age = SimpleImputer(strategy="mean", missing_values=np.nan)
Salary = SimpleImputer(strategy="mean", missing_values=np.nan)

age.fit(features[:, [1]])
Salary.fit(features[:, [2]])

features[:, [1]] = age.transform(features[:, [1]])
features[:, [2]] = Salary.transform(features[:, [2]])

print("\nAfter Handling Missing Values:")
print(features)

from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)

Country = oh.fit_transform(features[:, [0]])

print("\nOne Hot Encoded Country:")
print(Country)

final_set = np.concatenate((Country, features[:, [1, 2]]), axis=1)

print("\nFinal Set:")
print(final_set)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(final_set)

feat_standard_scaler = sc.transform(final_set)

print("\nStandard Scaled Data:")
print(feat_standard_scaler)

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler(feature_range=(0, 1))

mms.fit(final_set)

feat_minmax_scaler = mms.transform(final_set)

print("\nMin-Max Scaled Data:")
print(feat_minmax_scaler)

Original Data:
     Country   Age   Salary Purchased
0         UK  24.0  30000.0        No
1     Canada  31.0  57000.0       Yes
2  Australia  26.0  43000.0        No
3     Canada  43.0      NaN       Yes
4         UK  34.0  49000.0        No
5  Australia   NaN  61000.0       Yes
6     Canada  40.0  73000.0        No
7         UK  28.0  36000.0       Yes
8        NaN  52.0  91000.0        No
9  Australia  37.0  67000.0       Yes

After Handling Missing Values:
[['UK' 24.0 30000.0]
 ['Canada' 31.0 57000.0]
 ['Australia' 26.0 43000.0]
 ['Canada' 43.0 56333.333333333336]
 ['UK' 34.0 49000.0]
 ['Australia' 35.0 61000.0]
 ['Canada' 40.0 73000.0]
 ['UK' 28.0 36000.0]
 ['Australia' 52.0 91000.0]
 ['Australia' 37.0 67000.0]]

One Hot Encoded Country:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]

Final Set:
[[0.0 0.0 1.0 24.0 30000.0]
 [0.0 1.0 0.0 31.0 57000.0]
 [1.0 0.0 0.0 26.0 43000.0]
 [0.0 1.0 0.0 43.0 56333.33333